using Products.Models;
using Products.Models.DTOs;

namespace Products.Mappers;

/// <summary>
/// Mapper for converting between Product entities and DTOs
/// Implements the Adapter pattern to decouple domain models from API contracts
/// </summary>
public class ProductMapper : IProductMapper
{
  /// <summary>
  /// Converts a Product entity to a ProductDto for API responses
  /// </summary>
  public ProductDto ToDto(Product product)
  {
    if (product == null)
      throw new ArgumentNullException(nameof(product));

    return new ProductDto
    {
      Id = product.Id,
      UserId = product.UserId,
      Name = product.Name,
      Price = product.Price,
      ImageUrl = product.ImageUrl
    };
  }

  /// <summary>
  /// Converts a collection of Product entities to ProductDto collection
  /// </summary>
  public IEnumerable<ProductDto> ToDto(IEnumerable<Product> products)
  {
    if (products == null)
      throw new ArgumentNullException(nameof(products));

    return products.Select(ToDto);
  }

  /// <summary>
  /// Creates a new Product entity from a CreateProductDto
  /// Note: Id should be generated by the controller/service layer
  /// </summary>
  public Product ToEntity(CreateProductDto createDto)
  {
    if (createDto == null)
      throw new ArgumentNullException(nameof(createDto));

    return new Product
    {
      Id = string.Empty, // Will be set by the controller
      UserId = createDto.UserId,
      Name = createDto.Name,
      Price = createDto.Price,
      ImageUrl = createDto.ImageUrl
    };
  }

  /// <summary>
  /// Updates an existing Product entity with data from UpdateProductDto
  /// Only updates fields that are present in the DTO
  /// </summary>
  public void UpdateEntity(Product product, UpdateProductDto updateDto)
  {
    if (product == null)
      throw new ArgumentNullException(nameof(product));

    if (updateDto == null)
      throw new ArgumentNullException(nameof(updateDto));

    product.Name = updateDto.Name;
    product.Price = updateDto.Price;
    product.ImageUrl = updateDto.ImageUrl;
  }
}
